# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details

# Note: YAML anchors allow an object to be re-used, reducing duplication.
# The ampersand declares an alias for an object, then later the `<<: *name`
# syntax dereferences it.
# See http://blog.daemonl.com/2016/02/yaml.html
# To validate changes, use an online parser, eg.
# http://yaml-online-parser.appspot.com/

# Settings common to each job
anchor_1: &job_defaults
  # go expects specific checkout path representing url
  working_directory: /go/src/github.com/fabric8-services/fabric8-wit
  docker:
    # primary container = first one in list
    - image: circleci/golang:1.9
    - image: registry.centos.org/postgresql/postgresql:9.6
      environment:
        POSTGRESQL_ADMIN_PASSWORD: mysecretpassword
    - image: quay.io/openshiftio/fabric8-services-fabric8-auth:latest
      environment:
        AUTH_WIT_URL: "http://localhost:8080"
        AUTH_DEVELOPER_MODE_ENABLED: "true"
  environment:
    TEST_RESULTS: /tmp/test-results
    # The environment variables below are not needed by all steps below
    # but still specified on global level so we don't have to repeat them.
    F8_POSTGRES_HOST: localhost
    F8_POSTGRES_PORT: 5432
    F8_POSTGRES_USER: postgres
    F8_POSTGRES_PASSWORD: mysecretpassword
    F8_POSTGRES_DATABASE: postgres
    F8_POSTGRES_SSLMODE: disable

version: 2
jobs:

  setup-source:
    <<: *job_defaults   
    steps:
      - checkout
      - run: 
          name: Get Go dependencies
          command: make deps
      - run: 
          name: Generate code from design files and package assets as go files using bindata
          command: make generate
          
  prepare-tests-environment:
    <<: *job_defaults   
    steps:
      - run: 
          name: Get package that converts go test output to a junit XML report
          command: go get github.com/jstemmer/go-junit-report
      - run:
          name: Create test output directory
          command: mkdir -p $TEST_RESULTS/junit
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1

  go-code-analysis:
    <<: *job_defaults   
    steps:
      - run: make analyze-go-code

  go-code-format-check:
    <<: *job_defaults   
    steps:
      - run: make check-go-format

  run-unit-tests:
    <<: *job_defaults   
    steps:
      - run:
          name: "Run unit tests (without coverage)"
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test-unit.out > ${TEST_RESULTS}/junit/go-test-unit-report.xml" EXIT
            make test-integration-no-coverage | tee ${TEST_RESULTS}/go-test-unit.out
      #- run:
      #    name: "Run integration tests (without coverage)"
      #    command: |
      #      trap "go-junit-report <${TEST_RESULTS}/go-test-integration.out > ${TEST_RESULTS}/junit/go-test-integration-report.xml" EXIT
      #      make test-integration-no-coverage | tee ${TEST_RESULTS}/go-test-integration.out
      
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
          
  build-binaries:
    <<: *job_defaults   
    steps:
      - run:
          name: Build the server and client binaries
          command: make build
          
workflows:
  version: 2
  default_workflow:
    jobs:
      - setup-source
      - prepare-tests-environment      
      - go-code-analysis:
          requires:
            - setup-source
      - go-code-format-check:
          requires:
            - setup-source
      - run-unit-tests:
          requires:
            - prepare-tests-environment
      - build-binaries

