= Work item links: Design, Storage and REST API
:author: Konrad Kleine
:toc:
:toc-placement!:
:toc-title:Table of Contents
:toclevels: 5
:sectnums:
:experimental:

[abstract]
== Abstract
This document describes the what <<link,work item links>> and <<link-types,work
item link types>> are, and how you can manipulate them via the various REST
endpoints.

We also explain the reasons we for why we chose the layout as it is planned or
already implemented. This might involve a deep-dive into the way we store work
item <<link-typs,link types>> and <<link,links>> in our PostgreSQL database.

toc::[]

[[introduction]]
== Introduction

A work item has different fields depending on its work item type. The work item
types can be defined by an administrator.

Depending on the a project's needs and the chosen workflow, an administrator can
setup various work item types like for instance _epic_, _user-story_, _task_,
and so forth. Those work items alone don't make much sense as long as they are
not associated in a meaningful manner. For example, an _epic_ can have many
_user-stories_ as children, which in turn can have one to many _tasks_. But a
_user-story_ probably isn't going to have an _epic_ as a child. A work item of a
type _bug_ might block another bug or is a duplicate of another bug.

We call these associations between work items <<link,links>>.

For a full list of terms, see the <<glossary,glossary>>.  

[glossary]
[[Glossary]]
== Glossary

The following subsections list important terms when talking about work
item links. 

[[link]]
=== link
A link describes a _bidrectional_ relationship between two work items. That
means there's a defined <<source,source>> work item and a <<target,target>> work
item in a link. Their work item type is relevant. This allows us to create a
parent-child relationship among work items, like the one between an _epic_ and a
_user-story_, like we've explained in the above paragraph.

To realize this concept of a relationship between a source and a target in the
underlying storage, we will have to define a <<link-type,link type>>.

[[link-type]]
=== link type
A link type defines what work item types can be linked together and how their
relationship can be described.

[[link-category]]
==== link category
A <<link-type>> can have a category like `"system"`, `"extension"`, or `"user"`.

IMPORTANT: A user can only create, update, or delete, links in the `"user"`
<<link-category>>. Needless to say that a user can only create, update, or
delete <<link-type,link types>> with the link category `"user"`. This is a
security mechanism to prevent the user from breaking the system.

[[source]]
==== source
The source defines where the relationship between two work items starts. It
given as a work item ID. The type of work item that can be used as a source is
defined by the <<source-type>>. Read more about this in
<<storage-of-link-types>>.

[[source-type]]
===== source type
The <<source>> type specifies the type of work item that can be used as a
<<source>>.

[[target]]
==== target
The target defines where the relationship between two work items ends. It is
given as a work item ID. The type of work item that can be used as a target is
defined by the <<target-type>>. Read more about this in <<storage-of-link-types>>.

[[target-type]]
===== target type
The <<target>> type specifies the type of work item that can be used as a
<<target>>.

[[forward-name]]
==== forward name
The forward oriented path from <<source>> _to_ <<target>> is described with the
_forward name_. For example, if a bug _blocks_ a user story, the forward name is
`"blocks"`. See also <<reverse-name>>.

[[reverse-name]]
==== reverse name
The backwards oriented path from <<target>> _to_ <<source>> is described with
the _reverse name_. For example, if a bug _blocks_ a user story, the reverse
name name is `"blocked by"` as in: a user story is _blocked by_ a bug. See also
<<forward-name>>.


[[storage-of-link-types]]
== Storage of link types

A <<link-type,link type>> needs to have an `ID` field for easy referencing. A
`name` like i.e. `"blocker"` and `description` like `"prevents a bug from being
closed by another bug"` makes also sense. But at the very least we must also
specify the work item types for the <<source,source>> and the <<target,target>>.

Since a bidirectional relationship can be viewed from the <<source,source>> or
the <<target,target>>, it helps to specify words for each direction. Let's say,

> a bug B1 _blocks_ a bug B2.

If we put it the other way around,

> bug B2 _is blocked_ by B1.

We decided to include these words (_blocks_, and _blocked by_) in the
<<link-type,link type>> and refer to them as the <<forward-name>> and
<<reverse-name>>.

NOTE: We srongly believe that it helps us with internationalization (_i18n_) in
the long run to have english words for the <<forward-name>> and
<<reverse-name>>. With this information we have enough information to generate
output for a tool like link:https://en.wikipedia.org/wiki/Gettext[gettext] or
link:https://poedit.net/[Poedit]. But for now the texts just have a descriptive
purpose.

[[example-link-type-storage-layout]]
.Example of <<link type>> storage layout
|===
| ID| Name | Description | <<source-type>> | <<forward-name>> | <<target-type>> | <<reverse-name>> | <<link-category>>
| 0| epic-user-story-link | An epic can be the parent of a user story. | system.epic | parent | system.user-story | child | system
| 1| user-story-task-link | Tasks can be associated with a user story. | system.user-story|parent | system.task | child | system
| 2| bug-blocker | The source bug shall prevent the target bug from being closed. | system.bug | blocks | system.bug | blocked by | system
| 3| foo-bar | A <<link-type>> defined by the user | system.foo | ... | system.bar | ... | user
| 4| related | ... | * | related | * | related | user
|===

[[storage-of-links]]
== Storage of links

Storing a work item <<link,link>> is straight forward, now that we've layed out the <<link-type,link types>>.

[[example-link-storage-layout]]
.Example of link storage layout
|===
| ID| <<link-type>> | <<source>> | <<target>>
| 0| 2| 42| 333
|===

In the table <<example-link-storage-layout>> we store a <<link,link>> between
the <<source>> work item with ID `42` and the <<target>> work item with ID
`333`. Note that the <<link-type>> is `2`, hence it is a `bug-blocker` (See
table <<example-link-type-storage-layout>>) and the linked work items are bugs
(`"system.bug"`).

In other words we store the <<link>> that _bug 42_ blocks _bug 333_.

[[link-validation]]
=== Link validation

On creation of a new <<link>> we must validate that the two work items to be
linked can actually be linked. That means, a <<link-type>> must exist that has
the proper <<source>> and <<target>> work items types specified.

[[rest-interface]]
== REST interface

The REST interface for work item <<link,links>> lives under its own HTTP endpoint.

When we started the discussion on this topic we planned the REST endpoint to
live under the `api/workitems/<id>/links` endpoint. At first sight, it might make
sense to have `api/workitems/42/links` to query all <<link,links>> for the work
item with ID `42`. But on second thought, this endpoint schema doesn't allow you
to formulate a query for all blocked bugs because you always have a to have a
work item ID inside of the URL.

When we decided if <<link,links>> shall live under the REST endpoint `api/links`
or `api/workitems/links`, the latter endpoint made more sense at first because
it underlines that a <<link,link>> is meant for work items. But the downside is
that we cannot have a work item with an ID called `links` because that would be
addressed with `api/workitems/links`.

Hence, we went with the *`api/links`* and *`api/linktypes`* endpoints.

NOTE: We may implement a convenience endpoint eventually that looks like
`api/workitems/<id>/links` but it will not be the default way of dealing with
links for the work item with ID `<id>`.

The following sections deal with the specific endpoints for manipulating all
defined resources.

The table <<crud-matrix>> gives an overview of all the available actions and
their appropriate calls to endpoints. 

[[crud-matrix]]
.CRUD matrix
[cols="d,d,m,m"]
|===
|Resource |Action |Method |Endpoint

// Link categories

| <<link-category>> | <<create-link-category,Create>> | POST | api/linkcategories
| <<link-category>> | Fetch single | GET | api/linkcategories/<linkcategoryid>
| <<link-category>> | Fetch all | GET | api/linkcategories 
| <<link-category>> | Update | PUT | api/linkcategories/<linkcategoryid>
| <<link-category>> | Test for existence | HEAD | api/linkcategories/<linkcategoryid>

// Link types

| <<link-type>> | Create | POST | api/linktypes
| <<link-type>> | Fetch single | GET | api/linktypes/<linktypeid>
| <<link-type>> | Fetch all | GET | api/linktypes 
| <<link-type>> | Update | PUT | api/linktypes/<linktypeid>
| <<link-type>> | Test for existence | HEAD | api/linktypes/<linktypeid>

// Links

| <<link>> | Create | POST | api/links 
| <<link>> | Fetch single | GET | api/links/<linkid>
| <<link>> | Fetch all | GET | api/links 
| <<link>> | Update | PUT | api/links/<linkid>
| <<link>> | Test for existence | HEAD | api/links/<linkid>
|===

TODO: Include links like `/api/links/22/linktype` in order to get the link type
of link with ID 22

In general requests and response for CRUD operations are modeled after the
requests and responses you can find in the JSONAPI section on
link:http://jsonapi.org/format/#crud[CRUD].

[[create-link-category]]
=== Create link category

A normal user should not be allowed to create <<link-category,link categories>>.
This is a task that the system or an extension or plugin to the system should
only be allowed to execute. 

[[create-link-category-request]]
==== Request

In order to create a <<link-category>>, for a fictional `'test'` subsystem,
you would have to request it this way:

[source,json]
----
POST http://example.com/api/linkcategories/ HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": {
    "id": "0d05bba6-ef28-4032-9c79-0e2954bf76ce",
    "type": "linkcategories",
    "attributes": {
      "name": "subsystem_test",
      "title": "This category is reserved for link types that belong to the 'test' subsystem."
    }
  }
}
----

==== Responses

This section contains possible responses for a
<<create-link-category-request,link category creation request>>.

===== 201 Created

[source,json]
----
HTTP/1.1 201 Created
Location: http://example.com/api/linkcategories/subsystem_test
Content-Type: application/vnd.api+json

{
  "data": {
    "type": "linkcategories",
    "id": "subsystem_test",
    "attributes": {
      "name": "Test",
      "title": "This category is reserved for link types that belong to the 'test' subsystem."
    },
    "links": {
      "self": "http://example.com/api/linkcategories/subsystem_test"
    }
  }
}
----

===== 202 Accepted

[, JSONAPI-SPEC]
""
If a request to create a resource has been accepted for processing, but the
processing has not been completed by the time the server responds, the server
*MUST* return a `202 Accepted status` code.
""

===== 204 No Content

[, JSONAPI-SPEC]
""
If a `POST` request did include a Client-Generated ID and the requested resource
has been created successfully, the server *MUST* return either a `201 Created`
status code and response document (as described above) or a `204 No Content`
status code with no response document.
""

===== 403 Forbidden

[, JSONAPI-SPEC]
""
A server MAY return 403 Forbidden in response to an unsupported request to create a resource.
""

===== 404 Not Found

[, JSONAPI-SPEC]
""
A server MUST return 404 Not Found when processing a request that references a related resource that does not exist.
""

===== 409 Conflict

[, JSONAPI-SPEC]
""
A server *MUST* return `409 Conflict` when processing a `POST` request to create
a resource with a client-generated ID that already exists.

A server *MUST* return `409 Conflict` when processing a `POST` request in which
the resource object’s type is not among the type(s) that constitute the
collection represented by the endpoint.

A server *SHOULD* include error details and provide enough information to
recognize the source of the conflict.
""
===== Other Responses

[, JSONAPI-SPEC]
""
A server *MAY* respond with other HTTP status codes.

A server *MAY* include error details with error responses.

A server *MUST* prepare responses, and a client *MUST* interpret responses, in
accordance with HTTP semantics.
""

[[create-link]]
==== Create link 

[[open-questions]]
== Open questions

. Do we want to have <<link-type,link types>> per installation of the system or per project? 

... More to come here in detail ...

// [[fetch-all-link-types-response]]
// .Fetch all link types response
// [source,json]
// ----
// 200 OK
// Content-type: application/vnd.linktypes+json, application/json, text, plain
// 
// [{
//     "id": "1",
//     "name": "user-story-task-link", 
//     "desc": "Tasks can be associated with a user story.",
//     "source": "system.user-story",
//     "forwardName": "parent",
//     "target": "system.task",
//     "reverseName": "child"
// },
// {
//     "id": "2",
//     "name": "bug-blocker", 
//     "desc": "The source bug shall prevent the target bug from being closed.",
//     "source": "system.bug",
//     "forwardName": "blocks",
//     "target": "system.bug",
//     "reverseName": "blocked by"
// }]
// ----